// <auto-generated />
using System;
using EBonistika.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EBonistika.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EBonistika.API.Entities.Collection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Collections");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000001"),
                            Name = "Монеты Российской Империи"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000002"),
                            Name = "Советские монеты 1921–1991"
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000003"),
                            Name = "Современная Россия 1992–2025"
                        });
                });

            modelBuilder.Entity("EBonistika.API.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nominal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ObverseUrl")
                        .HasColumnType("text");

                    b.Property<string>("PurchaseCurrency")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("PurchaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("PurchasePrice")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("ReverseUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uuid");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.Property<int>("YearFrom")
                        .HasColumnType("integer");

                    b.Property<int>("YearTo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId");

                    b.HasIndex("SeriesId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1000001-0000-0000-0000-000000000000"),
                            CollectionId = new Guid("11111111-0000-0000-0000-000000000001"),
                            Condition = "XF",
                            Count = 1,
                            Country = "Российская Империя",
                            Currency = "Рубль",
                            Kind = "coin",
                            Nominal = "1",
                            Notes = "Куплена на аукционе, оригинальная патина, без следов чистки.",
                            PurchaseCurrency = "RUB",
                            PurchaseDate = new DateTimeOffset(new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PurchasePrice = 8500m,
                            SeriesId = new Guid("aaa10001-0000-0000-0000-000000000000"),
                            Year = 1797,
                            YearFrom = 1796,
                            YearTo = 1801
                        },
                        new
                        {
                            Id = new Guid("b1000002-0000-0000-0000-000000000000"),
                            CollectionId = new Guid("11111111-0000-0000-0000-000000000001"),
                            Condition = "VF",
                            Count = 1,
                            Country = "Российская Империя",
                            Currency = "Рубль",
                            Kind = "coin",
                            Nominal = "5",
                            Notes = "",
                            PurchaseCurrency = "RUB",
                            PurchaseDate = new DateTimeOffset(new DateTime(2025, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PurchasePrice = 12000m,
                            SeriesId = new Guid("aaa10001-0000-0000-0000-000000000000"),
                            Year = 1799,
                            YearFrom = 1796,
                            YearTo = 1801
                        },
                        new
                        {
                            Id = new Guid("b1000003-0000-0000-0000-000000000000"),
                            CollectionId = new Guid("11111111-0000-0000-0000-000000000001"),
                            Condition = "AU",
                            Count = 1,
                            Country = "Российская Империя",
                            Currency = "Рубль",
                            Kind = "coin",
                            Nominal = "10",
                            Notes = "Редкий год чеканки.",
                            PurchaseCurrency = "RUB",
                            PurchaseDate = new DateTimeOffset(new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PurchasePrice = 45000m,
                            SeriesId = new Guid("aaa10001-0000-0000-0000-000000000000"),
                            Year = 1801,
                            YearFrom = 1796,
                            YearTo = 1801
                        },
                        new
                        {
                            Id = new Guid("b1000004-0000-0000-0000-000000000000"),
                            CollectionId = new Guid("11111111-0000-0000-0000-000000000001"),
                            Condition = "VF",
                            Count = 2,
                            Country = "Российская Империя",
                            Currency = "Копейка",
                            Kind = "coin",
                            Nominal = "10",
                            Notes = "",
                            PurchaseCurrency = "RUB",
                            PurchaseDate = new DateTimeOffset(new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PurchasePrice = 2200m,
                            SeriesId = new Guid("aaa10002-0000-0000-0000-000000000000"),
                            Year = 1895,
                            YearFrom = 1894,
                            YearTo = 1917
                        },
                        new
                        {
                            Id = new Guid("b1000005-0000-0000-0000-000000000000"),
                            CollectionId = new Guid("11111111-0000-0000-0000-000000000001"),
                            Condition = "XF",
                            Count = 1,
                            Country = "Российская Империя",
                            Currency = "Рубль",
                            Kind = "coin",
                            Nominal = "1",
                            Notes = "Хранится в холдере PCGS.",
                            PurchaseCurrency = "RUB",
                            PurchaseDate = new DateTimeOffset(new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PurchasePrice = 9800m,
                            SeriesId = new Guid("aaa10002-0000-0000-0000-000000000000"),
                            Year = 1901,
                            YearFrom = 1894,
                            YearTo = 1917
                        },
                        new
                        {
                            Id = new Guid("b1000006-0000-0000-0000-000000000000"),
                            CollectionId = new Guid("11111111-0000-0000-0000-000000000001"),
                            Condition = "UNC",
                            Count = 1,
                            Country = "Российская Империя",
                            Currency = "Копейка",
                            Kind = "coin",
                            Nominal = "50",
                            Notes = "300-летие дома Романовых.",
                            PurchaseCurrency = "RUB",
                            PurchaseDate = new DateTimeOffset(new DateTime(2025, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PurchasePrice = 15000m,
                            SeriesId = new Guid("aaa10002-0000-0000-0000-000000000000"),
                            Year = 1913,
                            YearFrom = 1894,
                            YearTo = 1917
                        },
                        new
                        {
                            Id = new Guid("b2000001-0000-0000-0000-000000000000"),
                            CollectionId = new Guid("22222222-0000-0000-0000-000000000002"),
                            Condition = "VF",
                            Count = 3,
                            Country = "СССР",
                            Currency = "Копейка",
                            Kind = "coin",
                            Nominal = "1",
                            Notes = "Куплена на аукционе, оригинальная патина, без следов чистки. Хранится в холдере PCGS.",
                            PurchaseCurrency = "RUB",
                            PurchaseDate = new DateTimeOffset(new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PurchasePrice = 350m,
                            SeriesId = new Guid("aaa20001-0000-0000-0000-000000000000"),
                            Year = 1924,
                            YearFrom = 1921,
                            YearTo = 1957
                        },
                        new
                        {
                            Id = new Guid("b2000002-0000-0000-0000-000000000000"),
                            CollectionId = new Guid("22222222-0000-0000-0000-000000000002"),
                            Condition = "XF",
                            Count = 1,
                            Country = "СССР",
                            Currency = "Копейки",
                            Kind = "coin",
                            Nominal = "3",
                            Notes = "",
                            PurchaseCurrency = "RUB",
                            PurchaseDate = new DateTimeOffset(new DateTime(2025, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PurchasePrice = 700m,
                            SeriesId = new Guid("aaa20001-0000-0000-0000-000000000000"),
                            Year = 1931,
                            YearFrom = 1921,
                            YearTo = 1957
                        },
                        new
                        {
                            Id = new Guid("b2000003-0000-0000-0000-000000000000"),
                            CollectionId = new Guid("22222222-0000-0000-0000-000000000002"),
                            Condition = "AU",
                            Count = 2,
                            Country = "СССР",
                            Currency = "Копеек",
                            Kind = "coin",
                            Nominal = "20",
                            Notes = "Военная чеканка.",
                            PurchaseCurrency = "RUB",
                            PurchaseDate = new DateTimeOffset(new DateTime(2025, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PurchasePrice = 1200m,
                            SeriesId = new Guid("aaa20001-0000-0000-0000-000000000000"),
                            Year = 1943,
                            YearFrom = 1921,
                            YearTo = 1957
                        },
                        new
                        {
                            Id = new Guid("b2000004-0000-0000-0000-000000000000"),
                            CollectionId = new Guid("22222222-0000-0000-0000-000000000002"),
                            Condition = "VG",
                            Count = 1,
                            Country = "СССР",
                            Currency = "Копеек",
                            Kind = "coin",
                            Nominal = "50",
                            Notes = "",
                            PurchaseCurrency = "RUB",
                            PurchaseDate = new DateTimeOffset(new DateTime(2025, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PurchasePrice = 2500m,
                            SeriesId = new Guid("aaa20001-0000-0000-0000-000000000000"),
                            Year = 1925,
                            YearFrom = 1921,
                            YearTo = 1957
                        },
                        new
                        {
                            Id = new Guid("b2000005-0000-0000-0000-000000000000"),
                            CollectionId = new Guid("22222222-0000-0000-0000-000000000002"),
                            Condition = "UNC",
                            Count = 5,
                            Country = "СССР",
                            Currency = "Копейка",
                            Kind = "coin",
                            Nominal = "1",
                            Notes = "",
                            PurchaseCurrency = "RUB",
                            PurchaseDate = new DateTimeOffset(new DateTime(2025, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PurchasePrice = 120m,
                            SeriesId = new Guid("aaa20002-0000-0000-0000-000000000000"),
                            Year = 1961,
                            YearFrom = 1961,
                            YearTo = 1991
                        },
                        new
                        {
                            Id = new Guid("b2000006-0000-0000-0000-000000000000"),
                            CollectionId = new Guid("22222222-0000-0000-0000-000000000002"),
                            Condition = "XF",
                            Count = 2,
                            Country = "СССР",
                            Currency = "Копеек",
                            Kind = "coin",
                            Nominal = "10",
                            Notes = "",
                            PurchaseCurrency = "RUB",
                            PurchaseDate = new DateTimeOffset(new DateTime(2025, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PurchasePrice = 180m,
                            SeriesId = new Guid("aaa20002-0000-0000-0000-000000000000"),
                            Year = 1974,
                            YearFrom = 1961,
                            YearTo = 1991
                        },
                        new
                        {
                            Id = new Guid("b2000007-0000-0000-0000-000000000000"),
                            CollectionId = new Guid("22222222-0000-0000-0000-000000000002"),
                            Condition = "AU",
                            Count = 1,
                            Country = "СССР",
                            Currency = "Рубль",
                            Kind = "coin",
                            Nominal = "1",
                            Notes = "Последние годы СССР.",
                            PurchaseCurrency = "RUB",
                            PurchaseDate = new DateTimeOffset(new DateTime(2025, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PurchasePrice = 340m,
                            SeriesId = new Guid("aaa20002-0000-0000-0000-000000000000"),
                            Year = 1988,
                            YearFrom = 1961,
                            YearTo = 1991
                        },
                        new
                        {
                            Id = new Guid("b2000008-0000-0000-0000-000000000000"),
                            CollectionId = new Guid("22222222-0000-0000-0000-000000000002"),
                            Condition = "XF",
                            Count = 1,
                            Country = "СССР",
                            Currency = "Рубль",
                            Kind = "coin",
                            Nominal = "1",
                            Notes = "20 лет Победы.",
                            PurchaseCurrency = "RUB",
                            PurchaseDate = new DateTimeOffset(new DateTime(2024, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PurchasePrice = 1800m,
                            SeriesId = new Guid("aaa20003-0000-0000-0000-000000000000"),
                            Year = 1965,
                            YearFrom = 1965,
                            YearTo = 1991
                        },
                        new
                        {
                            Id = new Guid("b2000009-0000-0000-0000-000000000000"),
                            CollectionId = new Guid("22222222-0000-0000-0000-000000000002"),
                            Condition = "AU",
                            Count = 1,
                            Country = "СССР",
                            Currency = "Рубль",
                            Kind = "coin",
                            Nominal = "1",
                            Notes = "100 лет со дня рождения Ленина.",
                            PurchaseCurrency = "RUB",
                            PurchaseDate = new DateTimeOffset(new DateTime(2025, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PurchasePrice = 2400m,
                            SeriesId = new Guid("aaa20003-0000-0000-0000-000000000000"),
                            Year = 1970,
                            YearFrom = 1965,
                            YearTo = 1991
                        },
                        new
                        {
                            Id = new Guid("b2000010-0000-0000-0000-000000000000"),
                            CollectionId = new Guid("22222222-0000-0000-0000-000000000002"),
                            Condition = "UNC",
                            Count = 2,
                            Country = "СССР",
                            Currency = "Рубль",
                            Kind = "coin",
                            Nominal = "1",
                            Notes = "Олимпийские игры Москва-1980.",
                            PurchaseCurrency = "RUB",
                            PurchaseDate = new DateTimeOffset(new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PurchasePrice = 3200m,
                            SeriesId = new Guid("aaa20003-0000-0000-0000-000000000000"),
                            Year = 1980,
                            YearFrom = 1965,
                            YearTo = 1991
                        },
                        new
                        {
                            Id = new Guid("b3000001-0000-0000-0000-000000000000"),
                            CollectionId = new Guid("33333333-0000-0000-0000-000000000003"),
                            Condition = "VF",
                            Count = 3,
                            Country = "Россия",
                            Currency = "Рубль",
                            Kind = "coin",
                            Nominal = "1",
                            Notes = "",
                            PurchaseCurrency = "RUB",
                            PurchaseDate = new DateTimeOffset(new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PurchasePrice = 95m,
                            SeriesId = new Guid("aaa30001-0000-0000-0000-000000000000"),
                            Year = 1992,
                            YearFrom = 1992,
                            YearTo = 1998
                        },
                        new
                        {
                            Id = new Guid("b3000002-0000-0000-0000-000000000000"),
                            CollectionId = new Guid("33333333-0000-0000-0000-000000000003"),
                            Condition = "XF",
                            Count = 1,
                            Country = "Россия",
                            Currency = "Рублей",
                            Kind = "coin",
                            Nominal = "50",
                            Notes = "",
                            PurchaseCurrency = "RUB",
                            PurchaseDate = new DateTimeOffset(new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PurchasePrice = 200m,
                            SeriesId = new Guid("aaa30001-0000-0000-0000-000000000000"),
                            Year = 1993,
                            YearFrom = 1992,
                            YearTo = 1998
                        },
                        new
                        {
                            Id = new Guid("b3000003-0000-0000-0000-000000000000"),
                            CollectionId = new Guid("33333333-0000-0000-0000-000000000003"),
                            Condition = "AU",
                            Count = 1,
                            Country = "Россия",
                            Currency = "Рублей",
                            Kind = "coin",
                            Nominal = "500",
                            Notes = "Деноминация на подходе.",
                            PurchaseCurrency = "RUB",
                            PurchaseDate = new DateTimeOffset(new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PurchasePrice = 650m,
                            SeriesId = new Guid("aaa30001-0000-0000-0000-000000000000"),
                            Year = 1995,
                            YearFrom = 1992,
                            YearTo = 1998
                        },
                        new
                        {
                            Id = new Guid("b3000004-0000-0000-0000-000000000000"),
                            CollectionId = new Guid("33333333-0000-0000-0000-000000000003"),
                            Condition = "UNC",
                            Count = 5,
                            Country = "Россия",
                            Currency = "Рубль",
                            Kind = "coin",
                            Nominal = "1",
                            Notes = "Первый год после деноминации.",
                            PurchaseCurrency = "RUB",
                            PurchaseDate = new DateTimeOffset(new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PurchasePrice = 60m,
                            SeriesId = new Guid("aaa30002-0000-0000-0000-000000000000"),
                            Year = 1998,
                            YearFrom = 1998,
                            YearTo = 2014
                        },
                        new
                        {
                            Id = new Guid("b3000005-0000-0000-0000-000000000000"),
                            CollectionId = new Guid("33333333-0000-0000-0000-000000000003"),
                            Condition = "AU",
                            Count = 2,
                            Country = "Россия",
                            Currency = "Рубля",
                            Kind = "coin",
                            Nominal = "2",
                            Notes = "",
                            PurchaseCurrency = "RUB",
                            PurchaseDate = new DateTimeOffset(new DateTime(2025, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PurchasePrice = 80m,
                            SeriesId = new Guid("aaa30002-0000-0000-0000-000000000000"),
                            Year = 2001,
                            YearFrom = 1998,
                            YearTo = 2014
                        },
                        new
                        {
                            Id = new Guid("b3000006-0000-0000-0000-000000000000"),
                            CollectionId = new Guid("33333333-0000-0000-0000-000000000003"),
                            Condition = "XF",
                            Count = 3,
                            Country = "Россия",
                            Currency = "Рублей",
                            Kind = "coin",
                            Nominal = "10",
                            Notes = "",
                            PurchaseCurrency = "RUB",
                            PurchaseDate = new DateTimeOffset(new DateTime(2025, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PurchasePrice = 120m,
                            SeriesId = new Guid("aaa30002-0000-0000-0000-000000000000"),
                            Year = 2009,
                            YearFrom = 1998,
                            YearTo = 2014
                        });
                });

            modelBuilder.Entity("EBonistika.API.Entities.Series", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("YearFrom")
                        .HasColumnType("integer");

                    b.Property<int>("YearTo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId");

                    b.ToTable("Series");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaa10001-0000-0000-0000-000000000000"),
                            CollectionId = new Guid("11111111-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Павел I",
                            YearFrom = 1796,
                            YearTo = 1801
                        },
                        new
                        {
                            Id = new Guid("aaa10002-0000-0000-0000-000000000000"),
                            CollectionId = new Guid("11111111-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 30, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Николай II",
                            YearFrom = 1894,
                            YearTo = 1917
                        },
                        new
                        {
                            Id = new Guid("aaa20001-0000-0000-0000-000000000000"),
                            CollectionId = new Guid("22222222-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 2, 4, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Ранние советские монеты",
                            YearFrom = 1921,
                            YearTo = 1957
                        },
                        new
                        {
                            Id = new Guid("aaa20002-0000-0000-0000-000000000000"),
                            CollectionId = new Guid("22222222-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 12, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "После реформы 1961",
                            YearFrom = 1961,
                            YearTo = 1991
                        },
                        new
                        {
                            Id = new Guid("aaa20003-0000-0000-0000-000000000000"),
                            CollectionId = new Guid("22222222-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 21, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Юбилейные рубли",
                            YearFrom = 1965,
                            YearTo = 1991
                        },
                        new
                        {
                            Id = new Guid("aaa30001-0000-0000-0000-000000000000"),
                            CollectionId = new Guid("33333333-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 8, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Ельцинская эпоха",
                            YearFrom = 1992,
                            YearTo = 1998
                        },
                        new
                        {
                            Id = new Guid("aaa30002-0000-0000-0000-000000000000"),
                            CollectionId = new Guid("33333333-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 2, 19, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "После деноминации",
                            YearFrom = 1998,
                            YearTo = 2014
                        });
                });

            modelBuilder.Entity("EBonistika.API.Entities.Item", b =>
                {
                    b.HasOne("EBonistika.API.Entities.Collection", "Collection")
                        .WithMany()
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EBonistika.API.Entities.Series", "Series")
                        .WithMany("Items")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("EBonistika.API.Entities.Series", b =>
                {
                    b.HasOne("EBonistika.API.Entities.Collection", "Collection")
                        .WithMany("Series")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");
                });

            modelBuilder.Entity("EBonistika.API.Entities.Collection", b =>
                {
                    b.Navigation("Series");
                });

            modelBuilder.Entity("EBonistika.API.Entities.Series", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
